### ISSUE TITLE
export supported video to media

### ISSUE THREAD

**Issue by alpakeno** [TheOfficialFloW/VitaShell#150]
can VitaSHell export mp4 and other supported video files to media?

**Comment by limyz** [comment]
This issue isn't clear enough. If you are looking for mp4 playback, its currently not supported at this time.

**Comment by alpakeno** [comment]
I mean VitaShell export pictures to AVContent.db, so why not doing the same for videos?

**Comment by limyz** [comment]
Sorry @alpakeno for the late reply. Unless a supported library is made to work with VitaShell, then we can do the same for videos. I will reopen the issue for discussion with the other devs.

**Comment by TheOfficialFloW** [comment]
The request is totally valid: https://github.com/TheOfficialFloW/VitaShell/commit/371bcdd5689c7330f1d6fb1f53967f00a87d4c95

This feature is meant. Unfortunately the videoexport function hasn't been reversed yet in order to add it.

**Comment by limyz** [comment]
So far, only .bmp, .mp3, .jpeg and .png file extensions are supported. @TheOfficialFloW I assume the videoexport hasn't been reversed engineered yet?

**Comment by devnoname120** [comment]
@limyz No, it hasn't been reversed engineered. However, it has very few functions so it's safe to assume that it shouldn't take too long.

```yaml
  SceVideoExport:
    nid: 0x86B46C2D
    libraries:
      SceVideoExport:
        nid: 0xF0812A7C
        kernel: false
        functions:
          SceVideoExport_4F60A3C8: 0x4F60A3C8
      SceVideoExportEmpr:
        nid: 0x3BA9B5E8
        kernel: false
        functions:
          SceVideoExportEmpr_8493BF31: 0x8493BF31
      SceVideoExportData:
        nid: 0xFE94CA1D
        kernel: false
        functions:
          SceVideoExportData_3488EA69: 0x3488EA69
          SceVideoExportData_34953CC0: 0x34953CC0
          SceVideoExportData_8DDE620F: 0x8DDE620F
```
